tft_baseline:
  checkpoint_paths:
  - D:/skripsi/tft/models/tft_baseline/tft-baseline-epoch=18-val_loss=414.8535.ckpt
tft_with_sentiment:
  checkpoint_paths:
  - D:/skripsi/tft/models/tft_with_sentiment/tft-with-sentiment-epoch=05-val_loss=292.6086.ckpt
