tft_baseline:
  checkpoint_paths:
  - D:/skripsi/tft/models/tft_baseline/tft-baseline-epoch=14-val_loss=334.6898.ckpt
tft_with_sentiment:
  checkpoint_paths:
  - D:/skripsi/tft/models/tft_with_sentiment/tft-with-sentiment-epoch=06-val_loss=296.6952.ckpt
